#! /usr/bin/env node

// Relies upon Node.js because the browser can't load local files with XHR

var requirejs = require("./r")

requirejs.config({
  //Pass the top-level main.js/index.js require
  //function to requirejs so that node modules
  //are loaded relative to the top-level JS file.
  nodeRequire: require
})

requirejs(["./branch/parse", "fs"], function (parse, fs) {
  // TODO what the...? why is this "parse.json" and not "../parse.json"?
  fs.readFile("parse.json", { encoding: "UTF-8" }, function (err, data) {
    if (err) {
      throw err
    }
    data = JSON.parse(data)
    
    // TODO simple, but only works for arrays
    function iso(x, y) {
      if (Array.isArray(x)) {
        if (Array.isArray(y) && x.length === y.length) {
          for (var i = 0, iLen = x.length; i < iLen; ++i) {
            if (!iso(x[i], y[i])) {
              return false
            }
          }
          return true
        } else {
          return false
        }
      } else if (Array.isArray(y)) {
        return false
      } else {
        return x === y
      }
    }
    
    function print(x) {
      if (Array.isArray(x)) {
        return "(" + x.map(print).join(" ") + ")"
      } else {
        if (x === "") {
          return "\"\""
        } else {
          return "" + x
        }
      }
    }
    
    var passed = 0
      , failed = 0
    
    data.forEach(function (x) {
      try {
        var val = parse(x.text)
        if (x.value != null) {
          if (iso(val, x.value)) {
            ++passed
            //console.log("matched: " + print(val) + "\n         " + print(x.value))
          } else {
            ++failed
            console.log("did not match: " + print(val) + "\n               " + print(x.value))
          }
        }
        if (x.error) {
          ++failed
          console.log("expected error but got: " + print(val))
        }
      } catch (e) {
        if (x.error) {
          ++passed
          //console.log(e)
        } else {
          throw e
        }
      }
    })
    
    console.log(data.length + " tests: " + passed + " passed / " + failed + " failed")
  })
})